### ISSUE TITLE
this doesn't work

### ISSUE THREAD

**Issue by kris-at-ata** [amahon/docker-compose-data-science#1]
Not sure why this doesn't work, but here's the stack trace. I cloned the repo and ran docker-compose up. 

Starting docker-compose-data-science_postgres_1 ... done
Starting docker-compose-data-science_jupyter_1  ... done
Attaching to docker-compose-data-science_postgres_1, docker-compose-data-science_jupyter_1
postgres_1  | 2018-10-22 17:02:10.655 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2018-10-22 17:02:10.655 UTC [1] LOG:  listening on IPv6 address "::", port 5432
jupyter_1   | Container must be run with group "root" to update passwd file
jupyter_1   | Executing the command: jupyter notebook
postgres_1  | 2018-10-22 17:02:10.660 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-10-22 17:02:10.678 UTC [22] LOG:  database system was shut down at 2018-10-22 17:01:36 UTC
postgres_1  | 2018-10-22 17:02:10.685 UTC [1] LOG:  database system is ready to accept connections
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
jupyter_1   |     value = obj._trait_values[self.name]
jupyter_1   | KeyError: 'allow_remote_access'
jupyter_1   | 
jupyter_1   | During handling of the above exception, another exception occurred:
jupyter_1   | 
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
jupyter_1   |     addr = ipaddress.ip_address(self.ip)
jupyter_1   |   File "/opt/conda/lib/python3.6/ipaddress.py", line 54, in ip_address
jupyter_1   |     address)
jupyter_1   | ValueError: '' does not appear to be an IPv4 or IPv6 address
jupyter_1   | 
jupyter_1   | During handling of the above exception, another exception occurred:
jupyter_1   | 
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
jupyter_1   |     sys.exit(main())
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
jupyter_1   |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
jupyter_1   |     app.initialize(argv)
jupyter_1   |   File "<decorator-gen-7>", line 2, in initialize
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
jupyter_1   |     return method(app, *args, **kwargs)
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1629, in initialize
jupyter_1   |     self.init_webapp()
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
jupyter_1   |     self.jinja_environment_options,
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 158, in __init__
jupyter_1   |     default_url, settings_overrides, jinja_env_options)
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 251, in init_settings
jupyter_1   |     allow_remote_access=jupyter_app.allow_remote_access,
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
jupyter_1   |     return self.get(obj, cls)
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
jupyter_1   |     value = self._validate(obj, dynamic_default())
jupyter_1   |   File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
jupyter_1   |     for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
jupyter_1   |   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
jupyter_1   |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
jupyter_1   | socket.gaierror: [Errno -2] Name or service not known
docker-compose-data-science_jupyter_1 exited with code 1

Here's my docker info:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64

I'm running a Mac 10.13.6.

**Comment by ethancole** [comment]
I fixed this by removing 'numexpr==2.6.4' from the Dockerfile. I created a Fork and submitted a Pull request to merge. @amahon
